name: 01 Hello

on:
    push:
        branches: [master]
    
jobs:
    Saludar:
        runs-on: ubuntu-24.04
        steps:
            - name: Saludar
              run: echo `Hola desde GitHub Actions!`

            - name: Ver fecha de runner
              run: date

            - name: Ver archivos disponibles
              run: ls -la

    repo-files:
        runs-on: ubuntu-24.04
        steps:
            
            - name: Ver archivos disponibles
              uses: actions/checkout@v6
              
            - name: Ver archivos disponibles
              run: ls -la