name: 01 Hello
on: workflow_dispatch # La tarea pide ejecución manual desde la pestaña Actions con el evento workflow_dispatch
    
jobs:
    saludar:
        runs-on: ubuntu-24.04
        steps:
            - name: Saludar
              # run: echo `Hola desde GitHub Actions!`  # los backticks hacen que bash intente ejecutar el texto como un comando y el mensaje nunca se imprime o daría error
              run: echo "Hola desde GitHub Actions!"

            - name: Ver fecha de runner
              run: date

            - name: Ver archivos disponibles
              run: ls -la

    repo-files:
        runs-on: ubuntu-24.04
        steps:
            
            - name: Ver archivos disponibles
              uses: actions/checkout@v6
              
            - name: Ver archivos disponibles
              run: ls -la